name: renmoney_test
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  device_preview: ^1.0.0
  dio: ^4.0.5
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.3.1
  flutter_svg: ^1.0.3
  logger: ^1.1.0
  stacked: ^2.3.0
  stacked_services: ^0.8.17

dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  stacked_generator: ^0.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/product_sans/ProductSansRegular.ttf
          weight: 200
        - asset: assets/fonts/product_sans/ProductSansBold.ttf
          weight: 900
